# Generated by Django 4.2.5 on 2023-09-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=255)),
                ('postDescript', models.CharField(max_length=255)),
                ('dateCreate', models.DateField()),
                ('postCreator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
