# Generated by Django 4.2.5 on 2023-09-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_datecreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postCreator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
