# Generated by Django 4.2.5 on 2023-09-14 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_postcreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 0, 24, 56, 500987, tzinfo=datetime.timezone.utc)),
        ),
    ]
