# Generated by Django 4.2.5 on 2023-09-14 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments_alter_post_datecreate_post_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postComment',
        ),
        migrations.AddField(
            model_name='comments',
            name='creatorComment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 15, 57, 59, 926112, tzinfo=datetime.timezone.utc)),
        ),
    ]
