# Generated by Django 4.2.5 on 2023-09-15 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_postcomment_comments_creatorcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='creatorComment',
        ),
        migrations.AddField(
            model_name='post',
            name='postComments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 17, 38, 52, 564361, tzinfo=datetime.timezone.utc)),
        ),
    ]
