# Generated by Django 4.2.5 on 2023-09-15 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_remove_comments_creatorcomment_post_postcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='creatorComment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 17, 39, 52, 786310, tzinfo=datetime.timezone.utc)),
        ),
    ]
