# Generated by Django 4.2.5 on 2023-09-16 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_datecreate_alter_post_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 18, 6, 49, 228873, tzinfo=datetime.timezone.utc)),
        ),
    ]
