# Generated by Django 4.2.5 on 2023-09-16 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 18, 7, 22, 549249, tzinfo=datetime.timezone.utc)),
        ),
    ]
