# Generated by Django 4.2.5 on 2023-09-16 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 18, 8, 28, 431327, tzinfo=datetime.timezone.utc)),
        ),
    ]
